source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'Z3Network_Example' do
  pod 'Z3Network', :path => '../'
  target 'Z3Network_Tests' do
    inherit! :search_paths

    
  end
end
